### ISSUE TITLE
b:racer_experimental_completer is ignored (neovim)

### ISSUE THREAD

**Issue by sshilovsky** [racer-rust/vim-racer#102]
I tried to put `let b:racer_experimental_completer = 1` in ftplugin/rust.vim, but it seems to have no effect. Replacing `b:` with `g:` solves it though.

**Expected behaviour:**

`b:racer_experimental_completer` should be respected.

**Comment by Shougo** [comment]
Why the feature is needed?
Please explain it.

**Comment by Shougo** [comment]
This is the feature.

https://github.com/racer-rust/vim-racer/blob/master/README.md

**Comment by sshilovsky** [comment]
Not really strictly needed for me, `g:` is suitable for my purpose, but expected to work. It would help to keep cleaner configs without cloggering global variables namespace though.

**Comment by Shougo** [comment]
But the other variables have same problem.
I don't want to add the variables.
Why it is only in `g:racer_experimental_completer`?

**Comment by CodeSwimBikeRunner** [comment]
I'm sorry for the dumb question, but how do i get it working? I've installed the plugin and set that flag to true, but it doesnt happen automatically. Do i need to add something to vimrc?

**Comment by Shougo** [comment]
> Do i need to add something to vimrc?

`let g:racer_experimental_completer = 1` in your vimrc.
