### ISSUE TITLE
vim-racer conflicting with neocomplete?

### ISSUE THREAD

**Issue by jinks** [racer-rust/vim-racer#103]
I seem to have a weird cross interaction with vim-racer and neocomplete.

If you look at the following gif, you see what happen when I type `.unwrap()`. As you can see something is "eating" some of the letters. If I disable either vim-racer or neocomplete this doesn't happen. The letters that get eaten are not always the same, at another time I got `.uwrp()` as result.

![racer-complete](https://user-images.githubusercontent.com/285602/29498909-23488dc2-85fd-11e7-94b2-da1d3a4ad651.gif)

Both plugins are on default settings as per their READMEs.

I don't know what is causing this, so I can't really offer any debug information upfront. Please just ask for what you need.

**Comment by Shougo** [comment]
Hm.

I want to test the behavior.
Please create the minimal vimrc and the reproduce ways from Vim starting.

**Comment by jinks** [comment]
Here's a minimal vimrc that reproduces the error for me:
```vim
set nocompatible

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/bundle')
Plug 'Shougo/neocomplete.vim'
Plug 'racer-rust/vim-racer'
call plug#end()

let g:neocomplete#enable_at_startup = 1
```

Obviously you can replace the vim-plug part with any other method to get the plugs installed.

A test file (save as ./src/main.rs):
```rust
fn main() {
    println!("Hello, world!");
}
```

The error appears for me when I try to insert `.unwrap()` between the `)` and the `;`. (Note, `.unwrap()` is not a valid method at that point, but it still shouldn't mangle the input.)

Vim version is 8.0.0851.

**Comment by Shougo** [comment]
I will test it.

**Comment by Shougo** [comment]
I think your machine is very slow and the input is lost.
You can test it in another machine.

**Comment by jinks** [comment]
I doubt speed is the problem. i5-3550, 16G, data on SSD and there's almost no load.

Even if I type really slowly the changes happen and you can see the cursor jumping back and forth.

**Comment by Shougo** [comment]
Reproduced.
It is racer completion is too slow problem.
I cannot fix it.
You should use deoplete instead.

**Comment by jinks** [comment]
I might look into that, but I'm not *yet* on NeoVim. For now, YCM works for rust.

**Comment by Shougo** [comment]
> For now, YCM works for rust.

YCM has own integration with racer.
So it has not the problem.
