### ISSUE TITLE
Redraw issues with racer when scrolling in neovim

### ISSUE THREAD

**Issue by technetos** [racer-rust/vim-racer#106]
![1517683392](https://user-images.githubusercontent.com/10949810/35770427-0cef05e6-08e9-11e8-9a5f-bd2476bd2f97.png)

When I have a vertical split open like in the picture above and move around alot (scroll up and down) redraw of the divider seems to fail.  If I disable the racer plugin from loading this never happens.  

The text that spills over is from the split on the left, if I drag the divider left or right then it redraws and everything is fine.  

If someone could point out why this may be happening Id be happy to try and fix it myself.  

Neovim version:
NVIM v0.2.2

Platform:
Linux 4.14.15

EDIT: clarified the movement that causes this

**Comment by Shougo** [comment]
It is not vim-racer issue.
