### ISSUE TITLE
Completion not working

### ISSUE THREAD

**Issue by khlj** [racer-rust/vim-racer#107]
* racer complete command works on terminal.
* RACE_SRC_PATH is set
* racer binary path is set (*wasn't sure between foo/bar/bin or foo/bar/bin/racer, and tried both*).

I'm not really sure how  to make racer completion to work in vim.
I referred to #92  but so far problem persists.

**Comment by Shougo** [comment]
`RACE_SRC_PATH is set`

It must be ` RUST_SRC_PATH`.

**Comment by Shougo** [comment]
Please provide more information.
I cannot reproduce the problem.

Like this:

https://github.com/racer-rust/vim-racer/issues/94#issue-236558177

**Comment by Shougo** [comment]
> racer binary path is set (wasn't sure between foo/bar/bin or foo/bar/bin/racer, and tried both).

Please check `echo executable(racer#GetRacerCmd())`.
It must be 1.

**Comment by khlj** [comment]
Typo there. RUST_SRC_PATH is set.
and `echo executable(racer#GetRacerCmd())` returns 1.

And, that was just me being plain stupid. `C-x C-o` works.

However, I noticed when I run omnicomplete on p*r*, it doesn't show `print`. Is that normal behavior?

**Comment by Shougo** [comment]
If `C-x C-o` works, it is normal behavior.
vim-racer just calls racer directly.
