### ISSUE TITLE
ambiguous install instructions

### ISSUE THREAD

**Issue by rigelrozanski** [racer-rust/vim-racer#108]
within the `Readme.md` there is the line 

```
let g:racer_cmd = "/path/to/racer/bin"
```

nowhere is the path the racer bin ever described, maybe it's just because I'm a rust n00b, but still seems ambiguous - is there a default directory which can often be assumed here?

**Comment by Shougo** [comment]
You don't have to set `g:racer_cmd` manually.
Because, if it is not set `racer` is used.

**Comment by rigelrozanski** [comment]
@Shougo okay then is looks like step 3 should clearly reference that it is an optional step
