### ISSUE TITLE
Add support for a g:racer_enabled option to easily enable and disable the plugin

### ISSUE THREAD

**Issue by tngreene** [racer-rust/vim-racer#110]
I'd love it if there was a convenient way to disable the plugin for testing/usability purposes by setting some variable like

```VimL
:let g:racer_enabled = 0
```

Trying to set the g:racer_cmd to "" means it gives errors saying it can't find the racer executable.

**Comment by Shougo** [comment]
Why the feature is needed?
I don't understand.

vim-racer only works if you use vim-racer mappings.

**Comment by tngreene** [comment]
Hmmm.... I think I've messed up which plugins are responsible for autocomplete. Sorry about that. Closing
