### ISSUE TITLE
let g:racer_cmd = "/path/to/racer/bin" don`t working

### ISSUE THREAD

**Issue by fr0ster** [racer-rust/vim-racer#115]
Hi All

I have installed pugin by Vundle, I added Plugin 'racer-rust/vim-racer' into my Vim config.
When I have added let g:racer_cmd = "/path/to/racer/bin" into config, navigation don`t worked, I have message "Racer don`t find in $PATH".
When I have removed let g:racer_cmd = "/path/to/racer/bin", navigation started working fine.

Sorry for my bad English

Best regards, Aleksey Kislitsa

**Comment by Shougo** [comment]
It is dummy path.  You must replace the path to real path.  Closing.

**Comment by fr0ster** [comment]
Maybe i have bad English, but i don`t stupid, i have used REAL path to racer in my config and racer was found in console. If I set REAL path, plugin don`t worked, and all work if I don`t set.
Why do we need this variable?

**Comment by Shougo** [comment]
@fr0ster vim-racer uses `racer` command from `$PATH`.
But it may be not installed in the path.  So it is needed.

> but i dont stupid, i have used REAL path to racer in my config and racer was found in console.

You should check your path.  I think `:echo executable(g:racer_cmd)` is false.

**Comment by fr0ster** [comment]
Thanks for advices :)

Directory with racer was set in $PATH else i could`t to use racer in a shell.

When i set _**g:racer_cmd = "/home/alex/.cargo/bin"**_ plugin isn`t working and _**:echo executable(g:racer_cmd)**_ returned 0.
When i set _**g:racer_cmd = "home/alex/.cargo/bin/racer**"_ plugin is working and _**:echo executable(g:racer_cmd)**_ returned 1.

I`m propose change paragraph about **g:racer_cmd** from _let g:racer_cmd = "/path/to/racer/bin"_ to _let g:racer_cmd = "full_path_to_racer/racer"_
Maybe it`s will be more simple for understanding?

Thanks for plugin and exuuse me for my grumbling about small things, it`s very useful plugin :)

Best regards, Aleksey Kislitsa

**Comment by Shougo** [comment]
If the description is not easy to understand, you can fix it.  PR is welcome.

**Comment by fr0ster** [comment]
@Shougo I have created PR, thanks

**Comment by Shougo** [comment]
Merged.
