### ISSUE TITLE
Question install instructions.

### ISSUE THREAD

**Issue by Carreau** [racer-rust/vim-racer#12]
It seem like `set omnifunc=syntaxcomplete#Complete` is needed, or nothing works fro me.  Is that expected ?

Still it does not work perfectly C-x-C-o delete the start of the line before the token being completed. Am I doing something wrong ? Thanks.

**Comment by Shougo** [comment]
> It seem like set omnifunc=syntaxcomplete#Complete is needed, or nothing works fro me. Is that expected ?

You don't have to set the omnifunc.
vim-racer's omnifunc is set automatically.

**Comment by Carreau** [comment]
> You don't have to set the omnifunc.
> vim-racer's omnifunc is set automatically.

Hum, I cleaned my vim/folder and reinstall all plugin, you are right, it might have been a conflict with something else. 

Though It does not fix the fact that it erase the beginning of the line. I'm not sure why.

**Comment by ivanceras** [comment]
I'm experiencing the same with autocompletion
I type 

```
String::
```

then hit
`CTRL-x CTRL-o`
the buffer shows me the function list of String, but when I select the function I wanted, it just deletes the whole line and put the function name

**Comment by bluss** [comment]
I have the same issue. The project

**Comment by bluss** [comment]
I have the same line deletion issue. The project https://github.com/ebfe/vim-racer works well.

**Comment by Shougo** [comment]
@ivanceras @bluss @Carreau The problem seems be already fixed.
If another problem is occurred, please create new issue.

**Comment by kineticz** [comment]
I confirm that I need `set omnifunc=syntaxcomplete#Complete` to get autocompletion with vim 7.4.1707 on osx 10.11. 

Here is my .vimrc:

```
set nocompatible
if has('nvim')
  call plug#begin('~/.config/nvim/bundle')
else
  call plug#begin('~/.vim/bundle')
endif
Plug 'racer-rust/vim-racer'
Plug 'jiangmiao/auto-pairs'
" Plug 'rust-lang/rust.vim'
Plug 'scrooloose/nerdcommenter'
Plug 'tpope/vim-fugitive'
Plug 'int3/vim-extradite'
Plug 'ebfe/vim-racer'
call plug#end()

set hidden
"let g:racer_cmd = "/Users/kaiyin/.multirust/toolchains/nightly/cargo/bin/racer"
let $RUST_SRC_PATH="/Users/kaiyin/rust_source/rust/src"
set omnifunc=syntaxcomplete#Complete
setlocal tags=./rusty-tags.vi;/,$RUST_SRC_PATH/rusty-tags.vi
```

**Comment by Shougo** [comment]
@kindlychung Your vim-racer is the latest version?
The omnifunc is set by the below line.
https://github.com/racer-rust/vim-racer/blob/master/plugin/racer.vim#L213

You can check it by `:autocmd FileType rust`.

**Comment by kineticz** [comment]
Yes, it's set there, but not taking effect. Or maybe `RacerComplete` is not working.

**Comment by Shougo** [comment]
It is same with https://github.com/racer-rust/vim-racer/issues/39.
