### ISSUE TITLE
Completion adds the whole token

### ISSUE THREAD

**Issue by londospark** [racer-rust/vim-racer#120]
In Vim and GVim on Windows when I type `prin<C-x><C-o>` then select `println!` I see `prinprintln!` in the buffer instead of `println!`. 

A short [_vimrc](https://github.com/racer-rust/vim-racer/files/2407861/vimrc.txt) is attached in case the fault is in there.

**Comment by Shougo** [comment]
I don't reproduce the behavior.
`println!` cannot be completed.
I think SyntaxComplete is set in omnifunc.
Please check `omnifunc` value.

**Comment by Shougo** [comment]
I have tested in minimal vimrc and other method works properly.

**Comment by londospark** [comment]
What minimal vimrc and what other method? `set omnifunc=syntaxcomplete#Complete` doesn't seem to change anything.

Can we reopen this please?

**Comment by Shougo** [comment]
Here.

```vim
set runtimepath+=~/work/vim-racer
filetype plugin indent on
```

> Can we reopen this please?

If other people can reproduce the problem by above minimal vimrc, I will reopen it.

**Comment by londospark** [comment]
With that vimrc I was getting the error about omnifunc not being set, then once set as in my vimrc I got pattern not found.

**Comment by Shougo** [comment]
> With that vimrc I was getting the error about omnifunc not being set, then once set as in my vimrc I got pattern not found.

You need to change `~/work/vim-racer` to your vim-racer path.

**Comment by Shougo** [comment]
> then once set as in my vimrc I got pattern not found.

I got `pattern not found` to complete `println!`.

**Comment by londospark** [comment]
I also get `Pattern not found` for `std::io::B` where `racer complete std::io::B` gives me completions. I am using the minimal vimrc and now have the runtime path pointing to the correct place.

**Comment by londospark** [comment]
Now - I'm confused, it's all acting like you say it should (no `println!` completion and `std::io::B` completing to `std::io::Box`) Leaving this issue alone now. Many thanks for all your help.

**Comment by Shougo** [comment]
OK.
