### ISSUE TITLE
Open defination in a new tab

### ISSUE THREAD

**Issue by EricQAQ** [racer-rust/vim-racer#121]
Navigate to the identifier under the cursor and open it on a new tab:

In ftplugin/rust_racer.vim, add this line:

```
nnoremap <silent><buffer> <Plug>(rust-def-tab)
        \ :tab split<CR>:call racer#GoToDefinition()<CR>
```
so that we can use it in my `init.vim` like this:

```
au FileType rust nmap <C-w> <Plug>(rust-def-tab)
```

**Comment by fatedier** [comment]
Why not send PR to add this feature?

**Comment by Shougo** [comment]
You can add the PR.
