### ISSUE TITLE
Using ctrl-n for autocompletion to show up

### ISSUE THREAD

**Issue by gasabr** [racer-rust/vim-racer#124]
Sorry, if the question is duplicate, I was not able to find anything similar.

Can I somehow remap the <C-x><C-o> (or the underlying function) to just <C-n> to use the plugin the same way as default vim autocompletion? And can you, please, elaborate on why is <C-x><C-o> is the default mapping, have never encountered anything other than tab, <c-n> for autocompletion.

Thanks for the plugin!

**Comment by Shougo** [comment]
Like this.

`autocmd FileType rust inoremap <expr><buffer> pumvisible()? "\<C-n>" : "\<C-x>\<C-o>"`
