### ISSUE TITLE
No behaviour on Ubuntu

### ISSUE THREAD

**Issue by mishaszu** [racer-rust/vim-racer#125]
## Description
There is no vim-racer behavior on **Ubuntu 18.04.2 LTS**. No autocompletion, no errors, no warnings.

## Environment
1. I installed `racer` via `cargo`:
```sh
cargo +nightly install racer
```
2. I added `RACER_SRC_PATH` to `.zshrc` and sourced it. I can print variable into terminal. Checked, it's correct path.
```bash
export RACER_SRC_PATH="$HOME/.cargo/bin/racer"
```
3. I added `RUST_SRC_PATH` to `.zshrc` and sourced it. I can print variable into terminal. Checked, it's correct path.
```bash
export RUST_SRC_PATH="$HOME/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src"
```
4. Added `rust-src` component
```sh
rustup component add rust-src
```
5. Tested `racer` itself. It works.
```sh
racer complete std::io::B
```
6. Vim configuration:
```vim
call plug#begin('~/.vim/bundle')
Plug 'racer-rust/vim-racer', { 'for': 'rust'}
Plug 'rust-lang/rust.vim', { 'for': 'rust'}
Plug 'Chiel92/vim-autoformat', { 'for': 'rust'}
call plug#end()
    " # Racer
        let g:racer_cmd = $RACER_SRC_PATH
```
[Here is whole .vimrc](https://github.com/mishaszu/vim-rc/blob/master/vimrc)
7. Checked filetype with `echo &filetype` with result `rust`

## Extra note
Seems any Rust interaction in vim doesn't work properly. `YouCompleteMe` has autocompletion but doesn't show errors and warnings, `vim-autoformat` doesn't work too.
Other tools and languages works fine.

All checked with the newest `vim-racer`.

**Comment by Shougo** [comment]
Please check `omnifunc` works by `<C-x><C-o>`.

vim-racer just provide omnifunc and documentation jump features.

Other tools behavior is unrelated.

**Comment by Shougo** [comment]
> No autocompletion, no errors, no warnings.

`vim-racer` does not provide auto completion.

**Comment by mishaszu** [comment]
Oh right, that works! Sorry, I was thinking that it should automatically display all suggestions. I probably should look for another tool.
