### ISSUE TITLE
Completing something deletes the line.

### ISSUE THREAD

**Issue by Hoverbear** [racer-rust/vim-racer#13]
Completing any line such as `use std::` or `self.` shows the completion popup but also deletes everything on the current line.

Versions affected:
- VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Sep 28 2015 08:50:43)
- NVIM 0.1.0 (compiled Nov  2 2015 18:05:23)

Relevant config:

``` vim
" Racer
set hidden
let g:racer_cmd = '/home/hoverbear/.cargo/bin/racer'
let $RUST_SRC_PATH = '/home/hoverbear/git/rust/src/'
```

Spoke about in #12, but that's not the issue there so I split this off.

**Comment by bjonica** [comment]
Also having this issue. MacVim, GVim and terminal vim see this issue. I definitely didn't have it a couple of weeks ago with racer. Whenever completing something where the previous two characters were `::`, opening the completion menu erases the entire line.

**Comment by linduxed** [comment]
Confirming issue for NVIM 0.1.0.

**Comment by alexbool** [comment]
Also reproduces on my mac
