### ISSUE TITLE
Colorscheme configuration in vim-racer

### ISSUE THREAD

**Issue by sullivant** [racer-rust/vim-racer#132]
Could not find a related issue - but I currently run the 'rakr/vim-one' colorscheme.  The highlighting and background/foreground when vim-racer pops the menu seems to not align.

Do there exist configuration options for the vim-racer colors?

**Comment by Shougo** [comment]
Please set the highlights.

```
							*hl-Pmenu*
Pmenu		Popup menu: normal item.
							*hl-PmenuSel*
PmenuSel	Popup menu: selected item.
							*hl-PmenuSbar*
PmenuSbar	Popup menu: scrollbar.
							*hl-PmenuThumb*
PmenuThumb	Popup menu: Thumb of the scrollbar.
							*hl-Question*
```
