### ISSUE TITLE
Preview is not getting close

### ISSUE THREAD

**Issue by im-n1** [racer-rust/vim-racer#133]
Once I enable `let g:racer_experimental_completer = 1` and spawn completion a tiny preview buffer appears on the top of the screen. When I hit enter on a item from completion menu the preview is still visible even if it's not relevant anymore.

**Comment by Shougo** [comment]
This is Vim's feature.
If you want to close automatically:

```vim
autocmd CompleteDone * silent! pclose!
```

**Comment by im-n1** [comment]
Cool. Maybe it's worth to mention it in readme right next to `g:racer_experimental_completer`.
