### ISSUE TITLE
Compilation error (Android, Termux)

### ISSUE THREAD

**Issue by kykeon** [racer-rust/vim-racer#134]
Just went through an odyssey to get rust-nightly going on Android (aarch64-linux-android is not supported by rustup) to try to get racer to work, but this happens:

> [.......]
> Compiling rand_isaac v0.1.1
>    Compiling rand_hc v0.1.0
>    Compiling ena v0.13.0
>    Compiling lock_api v0.1.5
>    Compiling rustc_version v0.2.3
>    Compiling rustc-ap-rustc_cratesio_shim v491.0.0
>    Compiling crossbeam-epoch v0.3.1                                                                                                                            Compiling rand_os v0.1.3
>    Compiling num_cpus v1.10.1
>    Compiling jobserver v0.1.14
>    Compiling atty v0.2.11
>    Compiling rustc-hash v1.0.1
>    Compiling aho-corasick v0.7.4                                                                                                                               Compiling parking_lot_core v0.4.0
>    Compiling crossbeam-deque v0.2.0
>    Compiling quote v0.6.12
>    Compiling clap v2.33.0
>    Compiling parking_lot v0.7.1
>    Compiling rustc-ap-rustc_data_structures v491.0.0
>    Compiling rustc-ap-arena v491.0.0
> error[E0658]: use of unstable library feature 'alloc': this library is unlikely to be stabilized in its current form or name (see issue #27783)
>   --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-arena-491.0.0/lib.rs:24:1
>    |
> 24 | extern crate alloc;
>    | ^^^^^^^^^^^^^^^^^^^
>    |
>    = help: add #![feature(alloc)] to the crate attributes to enable
> 
> error: aborting due to previous error
> 
> For more information about this error, try `rustc --explain E0658`.
> error: Could not compile `rustc-ap-arena`.
> warning: build failed, waiting for other jobs to finish...
> error: failed to compile `racer v2.1.23`, intermediate artifacts can be found at `/data/data/com.termux/files/usr/tmp/cargo-installZuNhgd`
> 
> Caused by:
>   build failed

> $ cargo --version
> cargo 1.35.0-nightly

Any hope to get this going on Android?

**Comment by Shougo** [comment]
It is racer's issue.

Here is vim-racer's issue.
