### ISSUE TITLE
I don't get the idea of that plugin

### ISSUE THREAD

**Issue by xahon** [racer-rust/vim-racer#135]
`This plugin allows vim to use Racer ( on Apr 21) for Rust code completion and navigation.` but as far as I know vim uses things like `YouCompleteMe` or `deoplete` to provide code completion. I also don't know should I pair this plugin with https://github.com/rust-lang/rust.vim or they should be installed separately of each other.

**Comment by Shougo** [comment]
You need auto completion?
If it is need, you need to install auto completion framework like YouCompleteMe or deoplete.
But if it is not need, you can use manual completion `<C-x><C-o>` instead.
