### ISSUE TITLE
Should add an option to suppress stderr printout when racer panics

### ISSUE THREAD

**Issue by macthecadillac** [racer-rust/vim-racer#137]
### System info
OS: Debian 10
`nvim --version` output:
```
NVIM v0.3.7
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_UNIBI_HAS_VAR_FROM -I/home/mac/build_src/neovim/build/config -I/home/mac/build_src/neovim/src -I/home/mac/build_src/neovim/.deps/usr/include -I/usr/include -I/home/mac/build_src/neovim/build/src/nvim/auto -I/home/mac/build_src/neovim/build/include
Compiled by mac@debian

Features: +acl +iconv +jemalloc +tui
```

### Problem description:
Racer keeps crashing under certain conditions and when it does and does so frequently, neovim is practically unusable because of the constant stderr output (read once per keystroke--I'm not kidding). Things get bad enough that sometimes it wouldn't accept any of my input unless I exit insert mode.

### Minimal `init.vim`
```vim
call plug#begin('~/.config/nvim/vimplug')
Plug 'rust-lang/rust.vim'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'racer-rust/vim-racer'
call plug#end()

let g:deoplete#enable_at_startup = 0
augroup enable_deoplete
  autocmd!
  autocmd InsertEnter * call deoplete#enable() | autocmd! enable_deoplete
augroup END
 
if !exists('g:deoplete#omni#input_patterns')
  let g:deoplete#omni#input_patterns = {}
endif
let g:racer_cmd = $HOME . "/.cargo/bin/racer"
let g:racer_insert_paren = 0
```

### Steps to reproduce
Here is a MWE to crash racer: https://github.com/macthecadillac/mwe/blob/master/src/lib.rs

Proceed to the bottom of the file, start and new line, and type `impl_vec_eq_test!(f64: abs);`. Racer should crash and make deoplete print a bunch of stderr junk once you get to "6" and should continue doing so for every letter you type until you get to "a", at which point it will block you from inserting more text unless you type space or exit insert mode.

**Comment by macthecadillac** [comment]
Racer version: 2.1.25

**Comment by Shougo** [comment]
@macthecadillac 

Please test #138.

**Comment by Shougo** [comment]
> Racer should crash and make deoplete print a bunch of stderr junk once you get to "6" and should continue doing so for every letter you type until you get to "a", at which point it will block you from inserting more text unless you type space or exit insert mode.

It is racer problem instead of vim-racer.  Racer should not crash.

**Comment by Shougo** [comment]
Please upload `:mes` result.

**Comment by macthecadillac** [comment]
I know it is a racer problem but I thought it would be helpful for you guys if I describe the problem in full. I will file an issue at their repo at some point.

`:mes` results after the first trigger of a panic:
```
[deoplete] stderr from child process:b"thread 'searcher' panicked at 'visit_mac disabled b
y default', /home/mac/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-syntax-546.
0.0/visit.rs:114:9\nnote: run with `RUST_BACKTRACE=1` environment variable to display a ba
cktrace.\n"
[deoplete] stderr from child process:b'ERROR 2019-08-13T23:57:28.382360949Z: racer: Search
 thread panicked: Any\n'
```

I don't think #138 changes anything. The `:mes` results above are in fact the output with #138.

**Comment by macthecadillac** [comment]
Just to make it clear, that was with `g:racer_disable_errors` set to 1.

**Comment by Shougo** [comment]
OK.  So it must be fixed in deoplete side.
Because the check is implemented by deoplete instead of vim-racer.

I have added `check_stderr` option in deoplete.
You can disable the check.

**Comment by macthecadillac** [comment]
It works. Thanks
