### ISSUE TITLE
Unsure about completion behaviour

### ISSUE THREAD

**Issue by tostr7191** [racer-rust/vim-racer#139]
Hi

I am using neovim (`--HEAD`) on macOS (with deoplete). Recently I installed racer and also the rls with vim-ale. From reading the documentation it appears that racer is a subset of the rust language server. This to me would imply that using rls would give me the same completion (or more) than just racer. But looking at the autocomplete for something simple like
```
"random string".to<autocomplete here>
```
shows the methods `to_owned`, `to_lowercase` etc. with racer but none with rls. For a different completion:
```
"random string".in<autocomplete here>
```
the autocomplete results are identical between rls+ale/vim-racer.

My question is if this is intended behaviour and racer is a good idea even if rls is used or if this is a bug somwhere in my setup?

Best, tostr

**Comment by Shougo** [comment]
I don't know why the behavior occur.

You should ask it in `rls` issues instead of here.
