### ISSUE TITLE
How to Jump back when go to definition. like ctrl+T. (not ctrl+o)

### ISSUE THREAD

**Issue by carltraveler** [racer-rust/vim-racer#140]

**Comment by Shougo** [comment]
It is not implemented.

**Comment by Shougo** [comment]
I have checked the implementation.
The feature is already implemented, but you need to use the latest Vim/neovim.

**Comment by carltraveler** [comment]
my vim version:  VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)

**Comment by carltraveler** [comment]
ctrl+t can not work on my vim version

**Comment by carltraveler** [comment]
ok,get it.    https://github.com/vim/vim/commit/f49cc60aa802862c595ff619dccc11271633a94b
this commit fixed this issue

**Comment by Shougo** [comment]
Yes.  Your Vim version is very old unfortunately.
