### ISSUE TITLE
Error "E117: Unknown function: racer#RacerComplete

### ISSUE THREAD

**Issue by peshoicov** [racer-rust/vim-racer#142]
I installed racer globally and also I have the source installed by running `rustup component add rust-src`.

I have the plugin in `.vim/bundle/rust_racer/plugin/rust_racer.vim`, downloaded from the `ftplugin` folder from this repo.

And finally - in `.vimrc` I have:

```
set runtimepath^=~/.vim/bundle/rust_racer

" Set rust autocompletion tool "racer" ..
set hidden
let g:racer_cmd = "/home/petar/.cargo/bin/racer"
let $RUST_SRC_PATH="/home/petar/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src"
```

But when I open a rs  file and try Ctrl+x + Ctrl+o - I get this error:
`Error "E117: Unknown function: racer#RacerComplete`

Any ideas?

**Comment by Shougo** [comment]
You need to download the file.

https://github.com/racer-rust/vim-racer/blob/master/autoload/racer.vim

**Comment by peshoicov** [comment]
Thanks, @Shougo , after I downloaded the vim file from the autoload folder of the repo into an autoload folder inside the plugin folder (in .vim/bundle/rust_racer/autoload) - now it works.

(Why not add this to the README? ... as apparently it's necessary for the plugin to work?)

**Comment by Shougo** [comment]
> (Why not add this to the README? ... as apparently it's necessary for the plugin to work?)

Because, you should not download file manually.
You can clone the repository to `~/.vim/bundle/rust_racer`.

**Comment by rsanden** [comment]
I encountered this problem as well. According to the README, the suggestion to clone the repository to `~/.vim/bundle` is only for Pathogen users, and I am not using Pathogen.

Ultimately, I prefer to use [Vim 8 Packages](https://vimhelp.org/repeat.txt.html#packages) instead of a separate vim package manager. This is what worked for me:
```
# Install racer onto PATH
rustup component add rust-src

mkdir -p $HOME/.vim/pack/plugins/start
git clone https://github.com/racer-rust/vim-racer.git $HOME/.vim/pack/plugins/start/vim-racer

mkdir -p $HOME/.vim/plugin
ln -s $HOME/.vim/pack/plugins/start/vim-racer/ftplugin/rust_racer.vim $HOME/.vim/plugin/
```
I think this should be added to the README unless it's a bad way to install the package under Vim 8.

**Comment by Shougo** [comment]
Sorry.  I don't want to add package manager specific instructions.

**Comment by rsanden** [comment]
Vim 8 Packages is built into Vim 8. That's what I mean.
It's a way to use packages without needing a separate vim package manager.

**Comment by Shougo** [comment]
Yes, I know it is another plugin manager.
It is builtin though.
It depends on your configuration and to add instruction is endless.

**Comment by rsanden** [comment]
Okay, I understand.
Thanks for all of your work on this project. It's really great, and I appreciate it a lot.

**Comment by Shougo** [comment]
Thanks
