### ISSUE TITLE
Option to change default key bindings for completion

### ISSUE THREAD

**Issue by matu3ba** [racer-rust/vim-racer#144]
[Here](https://vi.stackexchange.com/questions/12394/change-keybinding-for-up-down-when-in-vim-popup) it is explained to change keybinding for autocompletion.
Is it okay to add to the README ? The default key bindings are inconvenient for fast typing.

`inoremap <expr> <C-j> pumvisible() ? "\<C-n>" : "\<C-j>"`
`inoremap <expr> <C-k> pumvisible() ? "\<C-p>" : "\<C-k>"`
`inoremap <expr> <C-l><C-l> pumvisible() ? "\<C-l><C-l>" : "\<C-x><C-o>"`

Or do you think a wrapper function would be worth the hassle?

**Comment by Shougo** [comment]
I think it is not needed in README.
Because it is not vim-racer related configuration.

> Or do you think a wrapper function would be worth the hassle?

I don't think the function is needed.
