### ISSUE TITLE
This autocomplete plugin not working in NeoVim

### ISSUE THREAD

**Issue by Extr3m4R4710** [racer-rust/vim-racer#147]
1. `RUST_SRC_PATH` is alweys set`.
2. `vim-racer` be installed and `g:racer_cmd` and again `g:racer_experimental_completer = 1`,`g:racer_insert_paren = 1` setting out.
3. `racer` always installd.
4. echo executable(racer#GetRacerCmd()) don't worked 
ERROR " zsh: parse error near `)' "

I don't speak English very well. but I can be understand to simple English Word.

`rustc 1.43.0-nightly (58b834344 2020-02-05)`
`cargo 1.42.0-nightly (9d32b7b01 2020-01-26)`
`racer 2.1.30`

**Comment by Shougo** [comment]
> echo executable(racer#GetRacerCmd()) don't worked

It must be executed in Vim command line instead of shell command line.
And to work the plugin, you need to type `<C-x><C-o>` in Vim insert mode.

**Comment by Extr3m4R4710** [comment]
it `<C-x><C-o>` is `<Ctrl-x><Ctrl-o>`? From before to nothing change.
This is my `vimrc`
Is something wrong?
```
call plug#begin('~/.vim/plugged')
Plug 'romainl/Apprentice'
Plug 'racer-rust/vim-racer'
call plug#end()

set number
set expandtab
set tabstop=4
set shiftwidth=4
set hidden

let g:racer_cmd = "$HOME/.cargo/bin/racer"
let g:racer_experimental_completer = 1
let g:racer_insert_paren = 1
```

**Comment by Extr3m4R4710** [comment]
Oh, and NeoVim was not `executable` function supported.
Then changed editor to  vim

**Comment by Extr3m4R4710** [comment]
pressing Ctrl-x then Ctrl-o worked!! 
Think you Shougo!! 
Arigato!!

**Comment by Shougo** [comment]
> Oh, and NeoVim was not executable function supported.

It works for me in Neovim.

**Comment by angguwulandari21** [comment]
[](url)
