### ISSUE TITLE
Always the same completion

### ISSUE THREAD

**Issue by linduxed** [racer-rust/vim-racer#15]
It seems like I always get the same list of completions provided, no matter what I position my cursor after. Of course, if I've already written `R` then only the ones starting with `R` will be provided as options, but the "source list" from which it will provide the suggestions seems to be the same every time.

The "available" completions are these:

```
AsMut AsRef Box Clone Copy Debug Decodable Default DoubleEndedIterator Drop
Encodable Eq Err ExactSizeIterator Extend FIXME Fn FnMut FnOnce From
FromPrimitive Hash Into IntoIterator Iterator NB NOTE None Ok Option Ord
PartialEq PartialOrd Rand Result RustcDecodable RustcEncodable Self Send Show
Sized SliceConcatExt Some String Sync TODO ToOwned ToString Vec XXX abstract
alignof as become bool box break char const continue crate display do else enum
extern f32 f64 false final fn for i16 i32 i64 i8 if impl in isize let loop
macro match mod move mut offsetof override priv pub pure ref return self size
sizeof static str struct super trait transparent true type typeof u16 u32 u64
u8 unsafe unsized use usize virtual where while
```

For a one-completion-per-line list, read [this gist](https://gist.github.com/linduxed/0251080e6874515bdc25).

**Comment by Shougo** [comment]
This problem is fixed by https://github.com/racer-rust/vim-racer/pull/20?

**Comment by Shougo** [comment]
#20 is merged.  Please test it again.

**Comment by Shougo** [comment]
@linduxed Ping

**Comment by linduxed** [comment]
Sorry for the absence, I'll test this soon.

**Comment by linduxed** [comment]
It seems like there's been no improvement on this front.

**Comment by Shougo** [comment]
OK.  I will test it.
Please create minimal .vimrc and reproduce ways from Vim starting.

**Comment by linduxed** [comment]
When I comment out or remove everything except the plugins `rust`, `vim-racer` and `rust.vim` then it seems like it works as it should.

I'll investigate what plugin/setting it is that's causing my above described issue.

**Comment by linduxed** [comment]
It seems like this was a configuration issue on my part all along. The plugin works as intended, sorry for reporting a false bug.

**Comment by Shougo** [comment]
OK.
