### ISSUE TITLE
Please provide <Plug>(rust-doc-tab) or other method to allow documents to be viewed in a new tab.

### ISSUE THREAD

**Issue by flw-cn** [racer-rust/vim-racer#150]
For many functions, the document is so long that it cannot be displayed in half the screen height, so it is a good choice if document can be displayed in a new Tab.

I tried to change the code in the `racer#ShowDocumentation()` function from `pedit` to `tab pedit`, I get the effect that I'm talking about, so I guess that would work.

**Comment by Shougo** [comment]
Yes.  You can implment the feature.
The PR is wellcome.
This is open source product.

**Comment by flw-cn** [comment]
Thank you for your encouragement, I have created a PR. Hopefully, it will be merged in.
