### ISSUE TITLE
E117: Unknown Function: racer#RacerComplete

### ISSUE THREAD

**Issue by mabushey** [racer-rust/vim-racer#154]
I compiled racer in a docker container as to not pollute my Ubuntu system. I copied the racer executable to my host system under `/usr/local/bin`:
```
$ racer -V
racer 2.1.37
```
```
cd ~/.vim/plugin
wget https://raw.githubusercontent.com/racer-rust/vim-racer/master/ftplugin/rust_racer.vim
```

I run vim on a `main.rs` file. In insert mode I type `use std::` then `ctrl-x xtrl-o`. I get:
`E117: Unknown Function: racer#RacerComplete` for 2 seconds and then it changes to `-- Omni completion (^O^N^P) Pattern not found`.

Any ideas??

**Comment by mabushey** [comment]
Some progress: I realized that while -V worked, lookups did not:
```
$ racer complete std::
Unable to find libstd under RUST_SRC_PATH. N.B. RUST_SRC_PATH variable needs to point to the *src* directory inside a rust checkout e.g. "/home/foouser/src/rust/src". Current value ""/home/michael/rust/scene-parse/src/libstd""
```

I was able to fix this via: `apt-get install rust-src` (Please add this to the docs, I had no clue this was a dependency)

```
$ racer complete std::
MATCH test,1,0,/usr/lib/rustlib/src/rust/src/libtest/lib.rs,Module,/usr/lib/rustlib/src/rust/src/libtest/lib.rs
MATCH alloc_crate,1,0,/usr/lib/rustlib/src/rust/src/liballoc/lib.rs,Module,/usr/lib/rustlib/src/rust/src/liballoc/lib.rs
...
```

Still doesn't work in vim. :(

**Comment by Shougo** [comment]
You need to install `autoload/racer.vim` in `~/.vim/autoload`.
```
cd ~/.vim/autoload
wget https://raw.githubusercontent.com/racer-rust/vim-racer/master/autoload/racer.vim
````

I don't recommend for you to use install the plugin manually.
Using plugin manager is recommended.

Because I think you don't know about plugin installation.

**Comment by mabushey** [comment]
I don't have a `~/.vim/autoload`, and I highly doubt that creating it will magically make it work.

> Because I think you don't know about plugin installation.

Welcome to the club.
