### ISSUE TITLE
No ouput from RacerDoc or RacerDef when space in file path

### ISSUE THREAD

**Issue by mikmaksi** [racer-rust/vim-racer#160]
This issue came up when using vim-racer with vim running from Windows Subsystem for Linux (WSL). 

Example Rust project directory: `/mnt/c/Users/First Last/source/new_proj`
Project directory doesn't have spaces, but the overall path does as frequently happens on Windows. No output is produced when calling RacerDoc or RacerDef.

After some troubleshooting I realized that `racer#ShowDocumentation` was running something of this form:
`/home/firstlast/.cargo/bin/racer complete-with-snippet 1 7 /mnt/c/Users/First Last/source/new_proj/src/main.rs /tmp/veiV3ko/4`. This command predictable errors out because of the space in the filename. 

I was able to fix this by modifying `racer.vim` on line 121 by wrapping `fname` in double quotes. I noticed wrapping of `fname` in double quotes already happens in `s:RacerGetExpCompletions` and `s:RacerGetCompletions`, so why not `racer#ShowDocumentation` or in `racer#GoToDefinition`?

Hopefully this is helpful to someone. Thank you!

**Comment by Shougo** [comment]
Fixed.
