### ISSUE TITLE
Ctrl+x + Ctrl+o does not work

### ISSUE THREAD

**Issue by murtyjones** [racer-rust/vim-racer#163]
Ctrl + x + Ctrl + o (using mac's control key) does not bring up any completions for me. Sometimes it brings up "pattern not found" and at other times it seems to bring up my vimrc or take me to the top of the file I'm editing.

I have racer installeed and working (the example command from the Racer readme returns the expected result)

## Racer / System info
macOS Catalina 10.15.7
`rustc 1.52.0-nightly (caca2121f 2021-03-05)`
`racer 2.1.44`
`echo $RUST_SRC_PATH:` `/Users/murtyjones/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library`

## `~/.vimrc`
```
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'racer-rust/vim-racer'

" All of your Plugins must be added before the following line
call vundle#end()            " required

" ... redacted

set hidden
let g:racer_cmd = "/Users/murtyjones/.cargo/bin/racer"
let g:racer_experimental_completer = 1
let g:racer_insert_paren = 1
```

**Comment by Shougo** [comment]
Have you read `:messages`?

```
Unable to find libstd under RUST_SRC_PATH. N.B. RUST_SRC_PATH variable needs to point to the *src* directory inside a rust checkout e.g. "/home/foouser/src/rust/src". Current
 value ""/home/shougo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd""
```

**Comment by Shougo** [comment]
`cargo +nightly install racer` fixed for me.

**Comment by Shougo** [comment]
Minimal vimrc

```vim
set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/src/vim-racer

let g:racer_cmd = "racer"
let g:racer_experimental_completer = 1
let g:racer_insert_paren = 1

filetype plugin indent on
```

**Comment by murtyjones** [comment]
Issue isn't resolved for me.

`:messages` has no info to offer.

> cargo +nightly install racer fixed for me.

this is the command i initially ran to install racer when i was setting up last night. i ran it again with `--force` just now, but no effect

> `set rtp+=~/src/vim-racer`

doesn't this require that i clone the repo? my vimrc looks similar other than `let g:racer_cmd = "/Users/murtyjones/.cargo/bin/racer"`

**Comment by Shougo** [comment]
> Issue isn't resolved for me.

Really????
Why it works for me?  Please explain.

vim-racer is really installed and worked?
vim-racer is open source and you can debug it easily.
You are not beginner.

> doesn't this require that i clone the repo? my vimrc looks similar other than let g:racer_cmd = "/Users/murtyjones/.cargo/bin/racer"

Your `rtp` is set by vundle plugin manager.  But I recommend for you to clone vim-racer and change rtp manually.  Because you may make mistake the plugin manager configuration.
You should check `setlocal omnifunc?`.

**Comment by Shougo** [comment]
```rust
extern crate uuid;

use uuid::Uuid;
use std::env;
us|
fn main() {
    let v = Vec::new();
    let u = Uuid::new_v4();
    u. // nothing shown after typing `.` until I press <C-x><C-o>.
    println!("Hello, world!");
}

```

The cursor is `|` position.  And you can press `<C-x><C-o>`.

**Comment by Shougo** [comment]
> at other times it seems to bring up my vimrc or take me to the top of the file I'm editing.

???  It is not `<C-x><C-o>` function.
Please provide the screen cast by `asciinema`.

https://asciinema.org/

**Comment by murtyjones** [comment]
In my case, the issue is that I was unaware `<C-x><C-o>` was intended to be executed while in `insert` mode, so I was leaving insert mode and attempting to execute it. I didn't know this because I am in fact a beginner with vim. Thanks for the help.

**Comment by Shougo** [comment]
Oh...
