### ISSUE TITLE
Deprecation notice?

### ISSUE THREAD

**Issue by EvanCarroll** [racer-rust/vim-racer#164]
According this [this site](https://jwilm.io/blog/youcompleteme-rust/),

> YouCompleteMe now supports Rust auto-completion and GoTo. Rust semantic analysis is provided by racerd, a JSON/HTTP server powered by racer. **YCM with Rust provides a superior experience to current vim-racer, emacs-racer, and other racer-based plugins.**

If that's true -- I'm not saying it is -- then perhaps notice should be added at the top of the page. To the extent that this method represents an inferior experience. And perhaps archiving the project and folding it up if so.

I'm only saying this because there are enough tools in the vim/rust space to make my head explode and YCM is the first one to claim superiority over another tool. If this statement is false, it would be great for someone to create a comparison.

**Comment by Shougo** [comment]
vim-racer is deprecated.  LSP feature is better than vim-racer.

I think LSP feature is better than YCM.  Because it is maintained well.

> To the extent that this method represents an inferior experience. And perhaps archiving the project and folding it up if so.

But I don't archive the project.  If you cannot LSP plugin, this project is still useful.
