### ISSUE TITLE
How to show function definition at bottom?

### ISSUE THREAD

**Issue by morefreeze** [racer-rust/vim-racer#19]
Just like https://github.com/phildawes/racer first screenshot of  `README.md`. How can vim show `pub fn as_mut_slice` at bottom?

**Comment by Shougo** [comment]
echodoc supports the documentation.
You need later Vim though.

https://github.com/Shougo/echodoc.vim

**Comment by morefreeze** [comment]
@Shougo Thanks for your reply and repo. But I still have no idea how to use it, I have read your doc in repo(https://github.com/Shougo/echodoc.vim/blob/master/doc/echodoc.txt). Could you give more detail or screenshot is better.

**Comment by johan-sun** [comment]
@morefreeze , you can add `let g:racer_experimental_completer = 1` to your `.vimrc`

**Comment by Shougo** [comment]
``` vim
let g:echodoc_enable_at_startup = 1
```

**Comment by morefreeze** [comment]
@johan-sun I had added it but vim doesn't show function definition. So I think it must be some other conf in my `.vimrc` disable this. Today I'll filter my `.vimrc` manually and find out which plugin disable it.

**Comment by morefreeze** [comment]
@Shougo I have added `let g:echodoc_enable_at_startup = 1` in `.vimrc`, but it still not display function definition, I set cmdheight `set cmdheight=3`.

I look over the source code, but I can't figure out when does `echodoc_dicts` add item? It seems `echodoc#register` will add item to `echodoc_dicts`, but I think nowhere invoke it.

Do I miss something?

**Comment by Shougo** [comment]
> I look over the source code, but I can't figure out when does echodoc_dicts add item? It seems echodoc#register will add item to echodoc_dicts, but I think nowhere invoke it.

The default echodoc_dict is available.
But you must use latest Vim(v:completed_item) feature is needed.
I think your Vim is too old.

And to print the documentation, you must complete the candidate.

**Comment by morefreeze** [comment]
I use Vim version 7.4.1016.

**Comment by Shougo** [comment]
@morefreeze Please describe the reproduce ways from Vim starting.  I will try it.

And echodoc is already works?

**Comment by morefreeze** [comment]
![image](https://cloud.githubusercontent.com/assets/1477233/12283692/bcfde79c-b9e3-11e5-953e-e1bea80bddf2.png)
I just follow behavior of racer screenshot.

This is my [.vimrc](https://gist.github.com/morefreeze/2f71160477c41de6f01b), I set `cmdheight=3` manually.

**Comment by Shougo** [comment]
@morefreeze You must select the candidate(for example `as_mut`) and insert it by `<C-y>`.

**Comment by morefreeze** [comment]
Aha, it seems work normally, but just only I don't select the candidate. It is solved.

Thank you very much @Shougo and your patient.
