### ISSUE TITLE
where is the rust src folder ?

### ISSUE THREAD

**Issue by deepseeksss** [racer-rust/vim-racer#23]
i'm using both linux and windows edtion rust, but there is no source folder....

is that meas i should download the rust souce code tar.gz and uncompress it to some place?

**Comment by Shougo** [comment]
> is that meas i should download the rust souce code tar.gz and uncompress it to some place?

Yes, racer uses the rust source code to complete standard library.

**Comment by acgxv** [comment]
Hello, @Shougo
Still need source code today?
I read the README and install plugin step by step. But there is not introduction about requiring source code.
Now, sometimes the suggestion doesn't show.
Even I got the suggestion, it was missing something, for example:
```
let mut a = vec![];
a.
```
I can see `into_iter()`, but `iter()`. When I tap 's', I can't find the `sort()` suggestion.
Seems it can't find the std lib?

**Comment by Shougo** [comment]
@AurevoirXavier 

Please see https://github.com/racer-rust/racer#configuration.
The configuration for racer is required.

**Comment by acgxv** [comment]
@Shougo I have already configure that. But still have this problem.
I see some blog that told me to add `let g:ycm_rust_src_path = '~/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src'` into .vimrc, but can't fix this problem.

**Comment by Shougo** [comment]
@AurevoirXavier I don't know about YouCompleteMe rust problem.
It should be asked it in YouCompleteMe issues.

**Comment by acgxv** [comment]
@Shougo Okay, thanks.
