### ISSUE TITLE
Prevent messages on vim startup

### ISSUE THREAD

**Issue by juanibiapina** [racer-rust/vim-racer#25]
Is there a way to prevent messages on vim startup if racer is not configured?

I'm currently using a fork that just "finishes" instead of printing messages, but it might make it difficult for people to debug.

If there was a way to print messages but not slow vim start up, it would be great.

**Comment by Shougo** [comment]
OK.  I will fix it.

**Comment by Shougo** [comment]
Fix the problems and few bugs.

**Comment by Shougo** [comment]
Merged.  Please test it.

**Comment by juanibiapina** [comment]
Tried it without setting RUST_SRC_PATH and I get a bunch of errors. I think some code might be broken.

**Comment by Shougo** [comment]
OK.  I will test it.
Please upload minimal .vimrc and reproduce ways from Vim starting.
And please upload the error messages.

**Comment by Shougo** [comment]
Please check your vim-racer is the latest version.
To upload your `git log | head` result in vim-racer directory.
