### ISSUE TITLE
press gd nothhing happend?

### ISSUE THREAD

**Issue by deepseeksss** [racer-rust/vim-racer#30]
how to fix ?

i see bottom show :call RacerGoToDefinition(), but nothing happend....no errors too.

**Comment by Shougo** [comment]
I don't know how this feature works.
Please upload the sample project file and reproduce ways.
I will try it.

**Comment by deepseeksss** [comment]
do you write rust code? 

it's quite simple to reproduce,

`use std::fs:File;`

`let mut f = try!(File::open("any file"));`

move the cursor on 'open', in normoal mode, press gd , may be goto the definition...

**Comment by Shougo** [comment]
OK.  I will test it later.
But it may be racer-rust problem.

Please test user defined function jump.
It does not work?

**Comment by deepseeksss** [comment]
yes, both not work...

**Comment by Shougo** [comment]
Please upload the user defined function example.
I will test it.

**Comment by deepseeksss** [comment]
```
fn add_one(num: &mut i32)
{
    *num += 1;
}

fn main() 
{
    let mut num = 0;
    add_one(&mut num);
    println!("num = {}", num);
}
```

**Comment by Shougo** [comment]
Thanks.

**Comment by Shougo** [comment]
I have fixed the error check.

This is the wrong code.

```
use std::fs:File;

let mut f = try!(File::open("any file"));
```

```
use std::fs::File;

let mut f = try!(File::open("any file"));
```

This is the correct code.
