### ISSUE TITLE
No matches returned if in middle of line

### ISSUE THREAD

**Issue by mxork** [racer-rust/vim-racer#32]
As in, 

`let mut writer = io::BufWriter::with_capacity(io:: );` 

returns `Pattern Not Found`. 

But,

`let mut writer = io::BufWriter::with_capacity(io::`

matches just fine. 

vim 7.4.963 Debian Testing. Reproducible with minimal vimrc, attached.

[vimrc-testing.txt](https://github.com/racer-rust/vim-racer/files/177192/vimrc-testing.txt)

**Comment by mxork** [comment]
Blame #20; seems a fix for YCM usage broke standard omnicomplete. I suggest rolling it back or editing the readme to say vim-racer is meant to be used with YCM.

**Comment by Shougo** [comment]
Reproduced.  #20 seems be broken...

**Comment by Shougo** [comment]
Fixed.
