### ISSUE TITLE
Deoplete auto-complete doesn't work

### ISSUE THREAD

**Issue by ferk6a** [racer-rust/vim-racer#34]
When typing text in a Rust file, I get the error `tempfile is not defined: line 91 on deoplete/sources/racer.py`. I tried to place an import at the start of the file (`import tempfile`), and the error is gone, but deoplete auto-completion in rust doesn't work at all.

However go-to definition works and manual omni-completion (C-X C-O) works ~~with static declarations (such as `std::thread::`), but not with dynamic code~~ (tested in another file and dynamic code works too).

I'm quite confused as I think it could be a configuration issue, my init.vim has these:

```
let g:racer_cmd = "/usr/bin/racer"
let $RUST_SRC_PATH = "/usr/src/rust/src"
let g:deoplete#enable_at_startup = 1
```

And I'm using vim-plug:

```
Plug 'Shougo/deoplete.nvim'
Plug 'racer-rust/vim-racer'
Plug 'zchee/deoplete-jedi'
```

And deoplete-jedi works fine.

**Comment by Shougo** [comment]
Reproduced.  It is bug.

**Comment by Shougo** [comment]
Fixed.
