### ISSUE TITLE
autocompletion not working correctly

### ISSUE THREAD

**Issue by kineticz** [racer-rust/vim-racer#39]
If I type `use std::pro` and then tab, the `pro` part is replaced by `__core`, which does not make sense at all.

**Comment by Shougo** [comment]
I cannot reproduce it.
Please create minimal .vimrc less than 50 lines and upload reproduce ways from Vim starting.

**Comment by kineticz** [comment]
Sorry, I meant `use std::pro` then c-x c-o.

**Comment by kineticz** [comment]
Ok, I have setup a minimal .vimrc and still have problems. If I type `std::en` then c-x c-o, I get this:

![](http://i.imgur.com/JjHslFk.png)

Which does not make sense at all according to racer:

``` bash
racer complete std::en
MATCH env,1,0,/Users/kaiyin/rust_source/rust/src/libstd/env.rs,Module,/Users/kaiyin/rust_source/rust/src/libstd/env.rs
```

My .vimrc:

```
set nocompatible
if has('nvim')
  call plug#begin('~/.config/nvim/bundle')
else
  call plug#begin('~/.vim/bundle')
endif
Plug 'racer-rust/vim-racer'
Plug 'jiangmiao/auto-pairs'
" Plug 'rust-lang/rust.vim'
Plug 'scrooloose/nerdcommenter'
Plug 'tpope/vim-fugitive'
Plug 'int3/vim-extradite'
call plug#end()

set hidden
"let g:racer_cmd = "/Users/kaiyin/.multirust/toolchains/nightly/cargo/bin/racer"
let $RUST_SRC_PATH="/Users/kaiyin/rust_source/rust/src"
set omnifunc=syntaxcomplete#Complete
setlocal tags=./rusty-tags.vi;/,$RUST_SRC_PATH/rusty-tags.vi
```

**Comment by Shougo** [comment]
@kindlychung It is Vim default behavior.  You can change the behavior by `noinsert` or `noselect`.
`:help completeopt`

**Comment by kineticz** [comment]
No, that's not the issue. The suggestions are **wrong**.

**Comment by Shougo** [comment]
OK.  I get it.  Your rust source is not rust type.

``` vim
" Plug 'rust-lang/rust.vim'
```

Please enable it.  It detects the rust filetype.

**Comment by moll** [comment]
I'm seeing the same thing on MacVim v7.4 (87). Typing `use std::en` and pressing `C-x C-o` results in `std::en` being replaced with `std::log`. `log` in my case is at the top of the autocomplete menu.

This is with the latest master from Rust.vim and Racer.vim repos.

**Comment by Shougo** [comment]
Reproduced.  It is the bug of the omnifunc.

**Comment by Shougo** [comment]
Fixed.

**Comment by moll** [comment]
That seems to have solved it. Thank you!
