### ISSUE TITLE
Method signature / documentation

### ISSUE THREAD

**Issue by tamasd** [racer-rust/vim-racer#49]
It would be really nice if either a short documentation or at least the method signature could be displayed when a cursor is on a method invocation.

**Comment by Shougo** [comment]
You can use echodoc for it.

https://github.com/Shougo/echodoc.vim

**Comment by tamasd** [comment]
EchoDoc only works when I type the code. It does nothing when I am reading existing code.

It would be really nice if vim-racer would have a similar functionality as vim-go, where it is possible to display the the type signatures under the cursor (automatically even), or I can open up the documentation easily in a split pane.

**Comment by Shougo** [comment]
You can read the documentation by pressing `K`.
So, the feature is already implemented.
