### ISSUE TITLE
AutoComplPop-like behaviour

### ISSUE THREAD

**Issue by msjyoo** [racer-rust/vim-racer#52]
Hello,

Any chance of AutoComplPop-like behaviour where completion is suggested automatically?

**Comment by Shougo** [comment]
`set completeopt+=noinsert`

**Comment by msjyoo** [comment]
@Shougo That doesn't seem to do anything? http://vimdoc.sourceforge.net/htmldoc/options.html#%27completeopt%27

**Comment by Shougo** [comment]
@sekjun9878 This documentation is too old.
Please refer the latest Vim documentation.

**Comment by msjyoo** [comment]
@Shougo That did not help at all :(

For others who found AutoComplPop too daunting to modify, I've found a solution here: https://github.com/roxma/SimpleAutoComplPop

**Comment by Shougo** [comment]
@sekjun9878 Please use latest Vim for it.
You don't have to use it.
https://github.com/vim/vim/blob/master/runtime/doc/options.txt#L1846

**Comment by msjyoo** [comment]
@Shougo I think you misunderstood me :P I meant having the omnicomplete triggered automatically, without having to press `<C-x><C-o>`. `noinsert` is just an option to not insert text as soon as `<C-x><C-o>` is pressed.

**Comment by msjyoo** [comment]
@Shougo Thanks for trying though, really appreciate it!!

**Comment by Shougo** [comment]
> @Shougo I think you misunderstood me :P I meant having the omnicomplete triggered automatically, without having to press <C-x><C-o>. noinsert is just an option to not insert text as soon as <C-x><C-o> is pressed.

OK.  You should use auto completion plugin

**Comment by zoumi** [comment]
How to set g:acp_behavior option for rust-vim in AutoComplPop?

**Comment by zoumi** [comment]
Here it is. Add it to your vimrc, you will find it works perfectly!:

```
let g:acp_behaviorRustOmniMethodLength = 0
let g:acp_behaviorKeywordCommand = "\<C-n>"
function! MeetsForRust(context)
  if g:acp_behaviorRustOmniMethodLength >= 0 &&
        \ a:context =~ '\(\.\|::\)\w\{' .
        \              g:acp_behaviorRustOmniMethodLength . ',}$'
    return 1
  endif
  return 0
endfunction

let g:acp_behavior = {
    \   'rust' : [
        \   {
        \   'command' : "\<C-x>\<C-o>",
        \   'meets'   : 'MeetsForRust',
        \   'repeat'  : 0,
        \   },
        \   {
        \   'command'      : "\<C-x>\<C-u>",
        \   'completefunc' : 'acp#completeSnipmate',
        \   'meets'        : 'acp#meetsForSnipmate',
        \   'onPopupClose' : 'acp#onPopupCloseSnipmate',
        \   'repeat'       : 0,
        \   },
        \   {
        \   'command' : g:acp_behaviorKeywordCommand,
        \   'meets'   : 'acp#meetsForKeyword',
        \   'repeat'  : 0,
        \   },
        \   {
        \   'command' : "\<C-x>\<C-f>",
        \   'meets'   : 'acp#meetsForFile',
        \   'repeat'  : 1,
        \   }
    \   ]
\   }
```
