### ISSUE TITLE
No racer executable found in $PATH

### ISSUE THREAD

**Issue by k0pernicus** [racer-rust/vim-racer#55]
Hi.

I installed `racer` and this plugin, and configure them.  
I can launch `racer` using `/Users/antonin/.cargo/bin/racer`, and it works!  
But, when I try `gd` in a simple line like `use std::`, Vim returns : 

```
No racer executable found in $PATH ...
:/Users/antonin/.cargo/bin/racer
:/Users/antonin/.cargo/bin...
```

And that's weird, because the `racer` executable is in the `PATH` environment :-/

Anyone here has a solution to test please?

**Comment by k0pernicus** [comment]
Ok, fixed this issue in replacing `$HOME` statement in `let g:racer_cmd = ...` by `/home/...`

**Comment by iamsebastian** [comment]
I also have this issue since few months. To replace a $var _(like $HOME)_ with a static string to home-directory should not be the solution, because I use my vim-config on different environments: Home office, office, dev. server, etc.
And I'm absolutely serious about that this issue did not exists, some few months ago.

**Comment by Shougo** [comment]
Fixed the problem

**Comment by iamsebastian** [comment]
Yeah. This fixed it. Thank you, @Shougo .

**Comment by k0pernicus** [comment]
Nice!

Thanks a lot @Shougo! 👍

**Comment by nullne** [comment]
@Shougo i met the same problem again.  could you help to fix it ?

**Comment by Shougo** [comment]
@nullne You need to check `g:racer_cmd` value and the path is executable.

**Comment by nullne** [comment]
@Shougo  i set the `g:racer_cmd` with the full abs path. it works after i changed it to `racer` 
thanks
