### ISSUE TITLE
No help page

### ISSUE THREAD

**Issue by mbyio** [racer-rust/vim-racer#56]
It would be nice to have a vim help page describing the various features and options for this plugin. Looking at the code, it looks like there are a number of variables that aren't actually listed in the README, and I didn't realize that it was setup to work with `K`.

**Comment by Shougo** [comment]
You can add it!

**Comment by mbyio** [comment]
I will try, though I might miss some features I don't know about (hence the issue). But I think the project needs a license before I can contribute to it. #41

**Comment by Shougo** [comment]
Please contact to @phildawes .
