### ISSUE TITLE
No behaviour.

### ISSUE THREAD

**Issue by Ploppz** [racer-rust/vim-racer#58]
I'm in linux using `nvim 0.1.4`.

I cloned `racer` into `~/work/rust/lib`, and ran `cargo build`.
In my vimrc:

```
Plug 'racer-rust/vim-racer'
set hidden
let g:racer_cmd='/home/ploppz/work/rust/lib/racer/target/debug/racer'
let $RUST_SRC_PATH='/home/ploppz/work/rust/lib/racer/src/'
```

But the plugin doesn't work. There's no useful completion, and hotkeys like `gd` don't do anything. It worked earlier. What changed since then is just that I cloned and built the `racer` repository anew.
(edit: [this](https://bpaste.net/show/ca609f078892) is `~/work/rust/lib/racer`)

**Comment by Shougo** [comment]
Please test if your racer works.
And you should ask the proper check method in racer repository
https://github.com/phildawes/racer/issues/591

**Comment by guingois** [comment]
Not sure if related but I sometimes get the same absence of behavior.

`racer` itself works fine on my setup. I followed the standard installation process and I can successfully use it with the command-line. As far as `vim-racer` is concerned, I've observed (with both `nvim` and `vim`) that:

When I open a Rust file directly, the plugin works fine. For example, `nvim main.rs` allows me to benefit from the plugin completion and hotkeys.

When I open a Rust file indirectly, the plugin does not work at all. For example, `nvim`, followed by the editor command `:e main.rs`, does not activate any of the plugin behavior.

This holds when I combine the two. For example:
1. `nvim foo.rs` => plugin OK.
2. `:edit bar.rs` => plugin KO.
3. `:buffer #` => plugin OK.

I hope it helps.

**Comment by Shougo** [comment]
You should check the buffer filetype.
I think it is not rust.

**Comment by simon-whitehead** [comment]
I also have this problem and can replicate it the same way @erwanthomas does.

Running: `vim src/main.rs` - everything works.
Running: `vim .` and using say, `NERDTree` to open the file - nothing works.

I ran this in both scenarios:

`echo &filetype`

Both of them return `rust`. Not sure how to proceed.

**Comment by guingois** [comment]
I've checked with a fresh Ubuntu install, installing only the bare minimum to  run racer, vim and vim-racer.
Same results, and like @simon-whitehead, `filetype` is `rust`.

**Comment by Shougo** [comment]
Hm. OK.  It should be fixed.
It is vim-racer bug.

**Comment by Shougo** [comment]
Please test the fix.
https://github.com/racer-rust/vim-racer/pull/77

**Comment by guingois** [comment]
Using your fix, I cannot replicate the problem anymore and the plugin works well. Thanks!

**Comment by Shougo** [comment]
Fixed.
