### ISSUE TITLE
Looks for completions in inactive vim window

### ISSUE THREAD

**Issue by Ploppz** [racer-rust/vim-racer#66]
Hello, I'm using neovim, and I split it up into several windows. My PC kept doing heavy work for a while, I could hear from the fans. And it turned out (htop) that racer was completing a line in a buffer that was in a vim windows that was not focused - several times apparently, with short bursts of 100% CPU but enough to keep my fans running. But after some minutes it stopped doing this alltogether.

**Comment by Shougo** [comment]
Because racer completion is slow.
I think last completion just did not be finished.

**Comment by Ploppz** [comment]
Oh, okay
