### ISSUE TITLE
Handle displaying signature like emacs plugin

### ISSUE THREAD

**Issue by oblitum** [racer-rust/vim-racer#7]
I don't use emacs but from racer screenshot at https://github.com/phildawes/racer one may expect to get more info than identifiers in vim too :-)

**Comment by sga001** [comment]
Write this in your .vimrc file: 

```
let g:racer_experimental_completer = 1
```

As you can tell from the name it is not fully functional. In particular, it shows function signatures (as shown in the emacs example), but it doesn't show things like the type of fields in a struct.

**Comment by oblitum** [comment]
@sga001 thanks for the info.

**Comment by msjyoo** [comment]
It would be nice if this info was in the README document.
