### ISSUE TITLE
"Go-back" support?

### ISSUE THREAD

**Issue by dpc** [racer-rust/vim-racer#80]
After setting up shortcuts (eg. `gd`) it works, but I'm unable to jump-back (typically `C-t`). Could it be supported as well?

**Comment by Shougo** [comment]
Please use `` instead.

**Comment by dpc** [comment]
That's not the same. \`\` will only bring back if the jump was to the same file, no?

**Comment by Shougo** [comment]
Please read the implementation.

https://github.com/racer-rust/vim-racer/blob/master/autoload/racer.vim#L216

vim-racer saves the position to `` register.
And it does not change the jump list.
`:keepjumps` is used and `cursor()` does not change the jump list.

**Comment by dpc** [comment]
I'm sorry - my vimscript-fu is poor. :) . All I know is that when I was testing it, it wasn't jumping back to the original file. Instead it jumped in the destination file back and forth (like \`\` normally does). Maybe I was testing wrong, or it was for other reason.

Also, (that's a different thing) the way I see it `gd` should provide a jump-back stack like the original `gd` and `C-t` does. I'm not sure if the code you pointed me to handles multiple jump-backs.

**Comment by Shougo** [comment]
The multiple jump-backs is not supported.

**Comment by rlei** [comment]
@dpc Ctrl+O (http://vim.wikia.com/wiki/Jumping_to_previously_visited_locations) works for jumping back.
