### ISSUE TITLE
Insertion position is wrong on below the second line

### ISSUE THREAD

**Issue by orumin** [racer-rust/vim-racer#81]
Completion string's insertion position is wrong while input some characters.

reproduction environment: 
init.vim https://gist.github.com/orumin/625c54835eef6db7b827725c1b8c45eb
ArchLinux Linux 4.9.6-1-zen
NeoVim 0.1.7
racer 2.0.4
dein.vim c786aa8686
deoplete.nvim e182a11a13
rust.vim 732b5fcb36
vim-racer 12f83600ed

e.g.)

I was typing as below:
```rust
use std::thread;
use std::tim
```
and using compeltion.

Expected completion result:
```rust
use std::thread;
use std::time
```
In reality:
```rust
use std::thread;
use std::timtime
```

**Comment by Shougo** [comment]
Fixed.
