### ISSUE TITLE
Completion in 'import' after curlies (deoplete)

### ISSUE THREAD

**Issue by theduke** [racer-rust/vim-racer#84]
Currently, with deoplete, there are no completions available after typing:

`import sd::io{E`

So autocomplete is not working inside the curlies.

This works fine with racer though. (`racer complete std::io::{E`).

What's missing to make this work?

**Comment by Shougo** [comment]
`g:deoplete#auto_complete_start_length`

You have inputted just `E`.
It is less than `g:deoplete#auto_complete_start_length`.

You can use manual completion using `deoplete#manual_complete()`.
