### ISSUE TITLE
Go to definition 

### ISSUE THREAD

**Issue by bluss** [racer-rust/vim-racer#86]
Go to definition works great :100: with https://github.com/ebfe/vim-racer and not with this plugin. Does anyone know why?

**Comment by Shougo** [comment]
Really?  I will test it.

Please create the minimal vimrc and the reproduce ways from Vim starting.
We have not ESP skills.

**Comment by bluss** [comment]
Sorry! it's my error. It's just because that plugin has gd enabled by default and this doesn't (anymore).

**Comment by bluss** [comment]
I have switched to this plugin since it works fine with new racer and the other doesn't. :+1:

**Comment by Shougo** [comment]
OK.

**Comment by pickfire** [comment]
`gd` works now but does it have `[d`, `]d` and all the other keys for tagsearch?

**Comment by Shougo** [comment]
You can add the feature.  It is OSS.
