### ISSUE TITLE
Add tag stack

### ISSUE THREAD

**Issue by twmb** [racer-rust/vim-racer#89]
`gd` currently exists to jump to a definition. Is it possible to add capabilities for a tag stack?

I imagine that `CTRL+]` could use the same underlying jump-to-definition functionality that `gd` uses, with the addition that `CTRL+T` could pop us back to the previous location.

I'd be interested in adding this myself, but don't know where to start.

**Comment by Shougo** [comment]
I think you need to add the feature in the function.
And you must add the `CTRL-T` keymapping for it.

https://github.com/racer-rust/vim-racer/blob/master/autoload/racer.vim#L176

**Comment by vext01** [comment]
I was about to report this also, but I see someone beat me to it.

**Comment by Shougo** [comment]
tag stack is the builtin function.
So we cannot extend it.

**Comment by asymmetric** [comment]
Could we add add-to-stack functionality to `rust-def` instead?

Don't know much of vim/neovim internals though :)

**Comment by Shougo** [comment]
> Could we add add-to-stack functionality to rust-def instead?

We cannot add/change the tag stack from Vim script.

**Comment by asymmetric** [comment]
I guess this can be closed then. Thanks!

**Comment by twmb** [comment]
How does cscope modify the tag stack, or vim-go? I'd be interested in pursuing whatever route they ended up taking.

**Comment by Shougo** [comment]
> How does cscope modify the tag stack, or vim-go? I'd be interested in pursuing whatever route they ended up taking.

cscope is builtin function.

**Comment by Shougo** [comment]
vim-go modify the tag stack?
Really?  I will check it.

**Comment by Shougo** [comment]
https://github.com/fatih/vim-go/blob/5db7dd6a618ffad89d270e97dbf47bf484747ad1/autoload/go/def.vim

vim-go does not change vim tag stack.
It just changes the jump list and the original stack.

**Comment by Shougo** [comment]
If you can, pull request is wellcome.

**Comment by shabbyrobe** [comment]
@Shougo, even if you don't necessarily want to work on this yourself, I don't think this issue should be closed until there's a proper resolution, whether that resolution happens here or in Vim itself (see issue [vim/vim#3336](https://github.com/vim/vim/issues/3336)). Tag stack keybindings usually work in vim language integration plugins. I use jedi-vim (python), vim-go and tsuquyomi (typescript) nearly every day and they all support this functionality; it's pretty much par for the course.

If it helps anyone, I found a plugin ([vim-tagimposter](https://github.com/idbrii/vim-tagimposter)) that lets you simulate the needed functionality with the following mapping:

```
au FileType rust nmap <C-]> :<C-u> TagImposterAnticipateJump <Bar> :call racer#GoToDefinition()<CR>
```

It seems you can't do `<Plug>(rust-def)` as it throws the dreaded "Trailing Characters" error.

`CTRL-T` works, as does `CTRL-]`. I ran into some trouble with functions that racer could not find - it puts it into the tag stack anyway. I will follow this up at the vim-tagimposter repo as well, maybe there's something silly I'm doing wrong. My vimscript knowledge is rudimentary at best. Here's a minimal reproducing example:

```
extern crate yep;

use std::io;
use std::io::prelude::*;
use std::fs::File;

fn main() -> io::Result<()> {
    let mut f = File::open("file_that_totally_exists.txt")?;
    let mut buffer = Vec::new();
    f.read_to_end(&mut buffer)?;
    Ok(())
}
```

If I try to jump to `read_to_end`, racer does not find the definition but the tag still appears in `:tags` and I have to pop it off myself with `CTRL-T`.

Still, progress is progress; I hope this helps somebody.

**Comment by Shougo** [comment]
OK.  I have reopened.  I don't work for it though.

**Comment by shabbyrobe** [comment]
No problem, that's totally reasonable, you've already done plenty for us by providing this plugin in the first place. Thank you for re-opening the issue.

I would hope that ultimately vim would be fixed to cater to this extremely common use case. If and when they fix vim, would you accept a PR to integrate with it?

**Comment by Shougo** [comment]
> If and when they fix vim, would you accept a PR to integrate with it?

Of course, yes.  I will check the PR.

**Comment by Shougo** [comment]
`settagstack()`/`gettagstack()` are added in Vim 8.1.0519.
You can implement the feature.

I will check the PR.
