### ISSUE TITLE
`gd` not working on Debian 8 /  neovim

### ISSUE THREAD

**Issue by vext01** [racer-rust/vim-racer#90]
In `init.vim`:

```
Plug 'racer-rust/vim-racer'
set hidden                                                                                               
let g:racer_cmd = "/home/vext01/.cargo/bin/racer"
au FileType rust nmap gd <Plug>(rust-def)                                                                
au FileType rust nmap gs <Plug>(rust-def-split)                                                          
au FileType rust nmap gx <Plug>(rust-def-vertical)                                                       
au FileType rust nmap <leader>gd <Plug>(rust-doc)
```

Racer is in the $PATH also:
```
$ which racer
/home/vext01/.cargo/bin/racer
```

Editting a file like this:
```
fn main() {                                                                                              
    let a = 1;                                                                                           
    println!("Hello, world! {}", a);                                                                     
}
```

Cursor over second instance of `a`:
  * `gd` does nothing.
  * `:call racer#GoToDefinition()` does nothing.

Hrm...

**Comment by Freyskeyd** [comment]
Same for me on MacOsx

**Comment by Shougo** [comment]
Please check `racer find-definition {line} {column} {file}` works.

**Comment by vext01** [comment]
Alright, here is the problem:

```
$ racer find-definition 3 src/main.rs 34
RUST_SRC_PATH environment variable must be set to point to the src directory of a rust checkout. E.g. "/home/foouser/src/rust/src"
```

Once set:
```
$ racer find-definition 3 34 src/main.rs 
MATCH a,2,8,src/main.rs,Let,let a = 1;
END
```

So I think you need to mention this in your `README.md`.

**Comment by vext01** [comment]
Deoplete-rust (a similar plugin) uses a vim variable for this. Not sure if that's a better route or not...

```
let g:deoplete#sources#rust#rust_source_path='/path/to/rust/src'
```

https://github.com/sebastianmarkow/deoplete-rust

**Comment by Shougo** [comment]
OK.  It should be.
I don't know why the error check is not implemented.

**Comment by fsouza** [comment]
@Shougo any way we can figure a different solution for that? ``RUST_SRC_PATH`` is not required when using rustup (and the rust-src component).

**Comment by Shougo** [comment]
> @Shougo any way we can figure a different solution for that? RUST_SRC_PATH is not required when using rustup (and the rust-src component).

If you have the different solution, please send the pull request.
