### ISSUE TITLE
`<Plug>(rust-def)` family re-open a current file being edited

### ISSUE THREAD

**Issue by yuttie** [racer-rust/vim-racer#97]
Calling `<Plug>(rust-def)` re-opens a current file, but I think it should be avoided by the if-statement at following line: https://github.com/racer-rust/vim-racer/blob/master/autoload/racer.vim#L247

In my environment, `a:filename` at the line is the full path to a source file containing a definition to jump.
However, `bufname('%')` is the relative path to a file of a current buffer, and comparing them results in `false`.

I think the condition of the if-statement should be `if a:filename != expand('%:p')`, but I'm not confident about it.

**Comment by yuttie** [comment]
I found this problem when I noticed that jumping to a definition resets the cursor position in other window of the same file, by the way.

**Comment by Shougo** [comment]
OK.  It should be.

**Comment by yuttie** [comment]
@Shougo Thanks.
I'll make a pull request later.

**Comment by Shougo** [comment]
:-)
